/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuadruplos;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ernes
 */
public class Cuadruplos extends javax.swing.JFrame {

    /**
     * Creates new form Cuadruplos
     */
    String cadena;
    int cont;
    ArrayList<String> operadores = new ArrayList<>();
    ArrayList<String> argumentos = new ArrayList<>();
    
    String titulos[] = {"Operador","Argumento 1","Argumento 2","Resultado"};
    String datos[] = new String[4];
    
    DefaultTableModel model;
    public Cuadruplos() {
        initComponents();
        cadena = "";
        cont = 1;
        nuevo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextPane();
        btn_calcular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_resultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txt_entrada.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Exprecion"));
        jScrollPane1.setViewportView(txt_entrada);

        btn_calcular.setBackground(new java.awt.Color(255, 255, 255));
        btn_calcular.setText("CALCULAR");
        btn_calcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Cuadruplos");

        t_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void nuevo(){
        model = new DefaultTableModel();
        model.setColumnIdentifiers(titulos);
        t_resultados.setModel(model);
    }
    
    private void calcular(){
        cadena = txt_entrada.getText().trim();
        String valor = "";
        cont = 1;
        operadores.add(".");
        nuevo();
        for (int i = 0; i < cadena.length(); i++) {
            switch(cadena.charAt(i)){
                case '(':
                    operadores.add(cadena.charAt(i)+"");
                    valor = "";
                    break;
                case ')':
                    if(!valor.equals("")){
                        argumentos.add(valor);
                        valor = "";
                    }
                    sacar_todo("(");
                    break;
                case '+': case '-':
                    if(!valor.equals("")){
                        argumentos.add(valor);
                        valor = "";
                    }
                    if(operadores.size()==1 || argumentos.size() < 2 || 
                            operadores.get(operadores.size()-1).charAt(0) == '('){
                        operadores.add(cadena.charAt(i)+"");
                    }else{
                        sacar(cadena.charAt(i)+"");
                    }
                    break;
                case '/': case '*':
                    if(!valor.equals("")){
                        argumentos.add(valor);
                        valor = "";
                    }
                    if(operadores.size()==1 || argumentos.size() < 2 || 
                            operadores.get(operadores.size()-1).charAt(0) == '('){
                        operadores.add(cadena.charAt(i)+"");
                    }else{
                        if(operadores.get(operadores.size()-1).charAt(0) == '+' ||
                                operadores.get(operadores.size()-1).charAt(0) == '-'){
                            operadores.add(cadena.charAt(i)+"");
                        }else{
                            sacar(cadena.charAt(i)+"");
                        }
                    }
                    break;
                default:
                    valor = valor + cadena.charAt(i);
                    break;
            }
        }
        
        if(!valor.equals("")){
            argumentos.add(valor);
            valor = "";
        }
        sacar_todo(".");
        datos[0] = "=";
        datos[1] = argumentos.get(argumentos.size()-1);
        datos[2] = "";
        datos[3] = "";
        model.addRow(datos);
        argumentos.remove(argumentos.size()-1);
    }
    
    private void sacar(String o){
        datos[0] = operadores.get(operadores.size()-1);
        operadores.remove(operadores.size()-1);
        datos[2] = argumentos.get(argumentos.size()-1);
        argumentos.remove(argumentos.size()-1);
        datos[1] = argumentos.get(argumentos.size()-1);
        argumentos.remove(argumentos.size()-1);
        datos[3] = "Aux"+(cont);
        cont++;
        argumentos.add(datos[3]);
        operadores.add(o);
        model.addRow(datos);
    }
    
    private void sacar_todo(String o){
        while(!operadores.get(operadores.size()-1).equals(o)){
            datos[0] = operadores.get(operadores.size()-1);
            operadores.remove(operadores.size()-1);
            datos[2] = argumentos.get(argumentos.size()-1);
            argumentos.remove(argumentos.size()-1);
            datos[1] = argumentos.get(argumentos.size()-1);
            argumentos.remove(argumentos.size()-1);
            datos[3] = "Aux"+cont;
            cont++;
            argumentos.add(datos[3]);
            model.addRow(datos);
        }
        operadores.remove(operadores.size()-1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadruplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadruplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadruplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadruplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadruplos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable t_resultados;
    private javax.swing.JTextPane txt_entrada;
    // End of variables declaration//GEN-END:variables
}
